spring:
  profiles:
    active: dev

server:
  port: 8084

user-service:
  url: http://localhost:8080/user-service

notification-service:
  url: http://localhost:8081/notification-service

email-server:
  get-emails-url: http://localhost:8082/api/emails
